# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://leanvalorization.com
title: Lea(r)n Valorization
email: peter.verhasselt@siris.be
author: Peter Verhasselt
description: Learn how improve your startup valuation.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/leanvalue
  - title: linkedin
    url: https://www.linkedin.com/pub/peter-verhasselt/1/8a0/392
