# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Lea(r)n Valorization
email: your-email@domain.com
baseurl: /leanvalorization
author: Your Name
description: > # "Write an awesome description for your new site here.
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/leanvalue
  - title: linkedin
    url: https://www.linkedin.com/pub/peter-verhasselt/1/8a0/392
